### ISSUE TITLE
Autoloading and Providing Lib Files

### ISSUE THREAD

**Issue by danielclucas** [d12frosted/environment#24]
This isn't an issue so much as a clarifying question. I hope that is okay. Let me know if there is a better place for me to ask!

I've noted that in your lib files in the emacs/lisp folder you autoload many of those functions and then you also provide those files. It's my understanding that autoloading is a way of providing files that don't need to be directly loaded. I also see that you don't require those lib files in any of the files where those autoloaded functions are used, so why do you provide them?

**Comment by d12frosted** [comment]
@danielclucas while not being an issue, I am totally fine with question here. 

Just to clarify, are you talking about `(provide 'lib-xxx)` in the bottom of files?

**Comment by danielclucas** [comment]
Yes, that is what I am referencing. I have been grappling with how to properly structure a configuration that is more modular. 

I see that in some cases you have non-internal functions that are not autoloaded in these lib files. 

Let me use an example that I am trying to understand. In `lib-vulpea-capture.el` you have the function `vulpea-capture-meeting` which is not autoloaded. You also don't require the package `lib-vulpea-capture.el` in `init-vulpea.el` so how is it that in the org-capture use-package block in `init-vulpea.el` you are able to bind "cm" to `vulpea-capture-meeting` and it knows what this function is? Does putting `provide lib-vulpea-capture` make the functions inside automatically available in the load path? 

I hope that question makes sense. I am trying to modularize my configuration and am still grappling with how to separate functions into files and how to best do so :smile:

**Comment by d12frosted** [comment]
Initially I wanted to write a very long post, but then I realized that your question is rather straight-forward and doesn't require 2000+ words long answer.

So... Because `vulpea-capture-setup` is being called before `vulpea-capture-meeting` is used. How?

https://github.com/d12frosted/environment/blob/b6a55cf6445790ea076374c14d2528d25da95c17/emacs/lisp/init-vulpea.el#L243-L258

Luckily, `use-package` has integration with `general` (or vice versa?). So what happens here - I bind some keys in the scope of `org-capture` feature. And these keybinding actually create a 'dependency' - whenever I use any of the bound keys, load `org-capture` feature. When it happens, `:config` block is being evaluated. Which in turn calls `(vulpea-capture-setup)`. This function is autoloaded:

https://github.com/d12frosted/environment/blob/b6a55cf6445790ea076374c14d2528d25da95c17/emacs/lisp/lib-vulpea-capture.el#L53-L54

That means that Emacs needs to load `lib-vulpea-capture` in order to call `vulpea-capture-setup`. Bam! And all other functions are loaded because file is loaded. So the call chain is the following. I press `M-m c m` → `org-capture` is loaded → `:config` is evaluated → `vulpea-capture-setup` requires loading of `lib-vulpea-capture` → `vulpea-capture-meeting` is defined → we go back to key binding mappings, which figures out that `vulpea-capture-meeting` needs to be called → call happens. We are happy.

That being said, my advice is the following - put autoload cookie on interactive functions, but don't put them on library functions. I am yet to following this advice lol.

Hope that helps.

**Comment by danielclucas** [comment]
Thank you so much for clarifying that! I understand now. 

Re your advice: I have seen other packages, such as doom, have libraries of autoloaded functions, so I assumed this is a way of organizing things and not loading functions which are not always necessary to load immediately.

**Comment by d12frosted** [comment]
> have libraries of autoloaded functions, so I assumed this is a way of organizing things and not loading functions which are not always necessary to load immediately.

Exactly, it doesn't contradict. The main idea of `lib-xxx` files is to be able to define functions on the top level (e.g. outside `use-package`), to get byte compiler hints (implies `require 'some-feature)` and to avoid eager loading of `some-feature`. You usually load it using autoloading mechanism, but there libraries (like `s.el` or `dash.el`) that should be loaded straight away. In general `autoload` cookies should be [used sparingly](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html).

P.S. Closing this issue, but we can continue our conversation :)
