### ISSUE TITLE
deprecated org-roam commands and a typo

### ISSUE THREAD

**Issue by qingshuizheng** [d12frosted/environment#5]
Hi Boris, 
Thanks for your excellent ideas on [Task Management with Org-roam](https://d12frosted.io/tags/org-roam.html), from which I benefit a lot.

I forked your emacs config and has been using it for a short period, seems that there are two small issues in case you wanna know:

1. According to [org-roam issue #1284](https://github.com/org-roam/org-roam/pull/1284),  `org-roam--get-title-or-slug` has been deprecated:
https://github.com/d12frosted/environment/blob/ac9d4dc10803e608ff0ddbb23e5bb5b55d5661bb/emacs/lisp/init-org.el#L512

2. According to [org-roam manual for completion](https://www.orgroam.com/manual.html#Link-Completions-Everywhere), `org-roam-completions-everywhere` should be `org-roam-completion-everywhere`:
https://github.com/d12frosted/environment/blob/7e9354aafd1ce895dc52407edaa707af9a99d8d5/emacs/lisp/init-org.el#L544

Correct me if I'm wrong.

Best 
Qingshui

**Comment by d12frosted** [comment]
Hi @qingshuizheng 

I am very happy that you find those ideas useful 😸 And it amazes me to hear that you have been using these configurations. And thank you for reporting these two issues. I will address them in #4 - a PR where I restructure my configurations (and clean them up along the way), because right now it's a mess (`org-notes` module, I am looking at you). Another goal I have in mind is to be able to run byte compiler and linters, so I could catch these kind of missconfigurations as soon as possible (upstream libraries change a lot and sometimes my code breaks, especially when I am using private APIs). I am going to run these checks on CI on a daily basis. If you wish, subscribe to #4 to get an update, when it's finished (right now I am at the stage of restructuring org related stuff). The branch is usable, but it still lacks a lot.

Cheers.

**Comment by qingshuizheng** [comment]
I always wanna build my own environment config and this would be my first try. Since your configs look nice and promising and I would like to give it a try and modify it as per the need. Love the osx and emacs parts a lot.

Indeed the upstream is changing rapidly and I'm glad to know that you're working on the revamping. Will definitely follow up on the #4.

Thanks for your sharing.

**Comment by d12frosted** [comment]
Wonderful to hear. I think that Emacs is a journey to experience, and writing personal configurations is a must. :100: 

> Love the osx and emacs parts a lot.

:heart: happy to hear

Have a great day @qingshuizheng

**Comment by qingshuizheng** [comment]
Aha! This is too true:
> Personal frustration and the biggest time waster in my life (comparable to video games). Please, turn away and retain your sanity. Otherwise you might end up tracking all your tasks, notes, thoughts and wine in Emacs.

Happy hacking and have a great day! @d12frosted
